[Interface]
PrivateKey = sPNFswdsnpwHbUgvfkP/TTEeZBiMyTg+fyOHu2yCn3g=
Address = 100.114.144.72/32
DNS = 10.255.255.2

[Peer]
PublicKey = IMHoX/bhNghQVQB0pYKi14pwJhkOcLevpiMa7Khaz2I=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 104.244.210.244:443
PresharedKey = 2gdHUOhsRzBvSY1rJN0luArYKKE3UgXySxLTSYEcQQg=
