[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[BitTorrent]
Session\BTProtocol=Both
Session\DefaultSavePath=/downloads
Session\ExcludedFileNames=
Session\InterfaceAddress=100.114.144.72
Session\Port=2517
Session\QueueingSystemEnabled=false
Session\TempPath=/downloads/temp
Session\TempPathEnabled=true
Session\UseRandomPort=true

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=6

[Network]
Cookies=@Invalid()

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\Address=
WebUI\HostHeaderValidation=false
WebUI\Password_PBKDF2="@ByteArray(lSB4NbjfX2ZVXR3q7XdkdQ==:yuTU7/rTTv+Yp1x16Mh554iB1IjTYNdOFAPoncxxJmoZaAR8kh3MCgi42a8Vljuu4NnfQMTgCEC0okcXQn6yGA==)"
WebUI\Port=8080
WebUI\Username=belles

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
